config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'welcome#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users, only: [:create, :new, :show] do
    resources :concerts, except: [:index]
  end

  namespace :admin do
    resources :genres, only: [:new, :create, :destroy, :index]
    resources :images, only: [:new, :create]
    get '/dashboard', to: 'admin#dashboard'
  end

  resources :images, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :classification, presence: true
  has_many :concerts, dependent: :destroy
end

app/models/concert.rb
class Concert < ApplicationRecord
  include ActionView::Helpers::DateHelper
  validates :name, presence: true, length: { in: 0..25 }
  belongs_to :user
  belongs_to :genre
  has_many :concert_images, dependent: :nullify
  has_many :images, through: :concert_images
  scope :name_like, -> (name) { where("concerts.name LIKE ?", "%#{name}%") }

  def self.per_page
    4
  end

  def time_ago
    time_ago_in_words(updated_at)
  end

  def time_until
    distance_of_time_in_words(Time.now, date)
  end

  def purchased?
    if purchased == true
      "Yes"
    else
      "No"
    end
  end

  def readable_date
    date.strftime("%A - %B %e, %Y")
  end
end

app/models/concert_image.rb
class ConcertImage < ApplicationRecord
  belongs_to :concert
  belongs_to :image
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :classification, presence: true
  has_many :concerts, dependent: :destroy

  def self.per_page
    10
  end
end

app/models/ideaimage.rb
class IdeaImage < ApplicationRecord
  has_many :ideas
  has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :concert_images
  has_many :concerts, through: :concert_images, dependent: :destroy

  def self.per_page
    8
  end
end

app/models/session.rb
class Session < ApplicationRecord


end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true
  validates_confirmation_of :password
  has_secure_password
  has_many :concerts
  enum role: ["default", "admin"]
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < Admin::BaseController

  def dashboard
    @genres = Genre.order(:classification).paginate(:page => params[:genres_page])
    @images = Image.order(:name).paginate(:page => params[:images_page])
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::BaseController

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash.now[:success] = "Genre Successfully Created"
      redirect_to admin_dashboard_path
    else
      flash[:failure] = "Genre Not Created"
      render :new
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy

    redirect_to admin_dashboard_path
  end

  def index
    @genres = Genre.all
  end

  private

    def genre_params
      params.require(:genre).permit(:classification)
    end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController
  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:success] = "You've created an image."
      redirect_to admin_dashboard_path
     else
       render :new
    end
  end

  private

    def image_params
      params.require(:image).permit(:image, :name)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include CollectionsHelper
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: [:edit, :update, :destroy, :show]
  before_action :set_user, only: [:new, :create, :edit, :update]

  def new
    @concert = Concert.new
    @genres = Genre.order(:classification)
    @images = Image.order(:name)
  end

  def create
    @genres = Genre.order(:classification)
    @images = Image.order(:name)
    @concert = @user.concerts.new(concert_params)
    if @concert.save!
      @concert.concert_images.create(image_id: params[:concert][:image_ids].to_i)
      flash[:success] = "Concert successfully created."
      redirect_to user_path(current_user)
    else
      flash[:failure] = "Concert not created."
      render :new
    end
  end

  def edit
    @genres = Genre.order(:classification)
    @images = Image.order(:name)
  end

  def update
    concert = @concert
    concert.update(concert_params)
    @concert.concert_images.update(image_id: params[:concert][:image_ids].to_i)
    flash[:success] = "Concert successfully edited."
    redirect_to user_path(current_user)
  end

  def show

  end

  def destroy
    @concert.destroy

    redirect_to user_path(current_user)
  end

  private

    def concert_params
      params.require(:concert).permit(:name, :purchased, :date, :genre_id, {:image_ids => []})
    end

    def set_concert
      @concert = Concert.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.order(:name).paginate(:page => params[:page])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @session = Session.new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      flash[:success] = "You're now logged in, #{@user.name}."
      redirect_to user_path(@user)
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    @user = User.find_by(params[:id])
    log_out
    flash[:notice] = "You're now logged out."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Concert Box, #{@user.name}!"
      redirect_to user_path(@user)
    else
      flash[:failure] = ""
      render :new
    end
  end

  def new
    @user = User.new
  end

  def show
    @search = ConcertSearch.new(search_params)
    @concerts = @search.results.order(:date).paginate(:page => params[:page])
    @user = User.find(params[:id])
    @genres = Genre.order(:classification)
    @concert_images = ConcertImage.all
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

  protected
    def search_params
      (params[:concert_search] || {}).merge(user_id: current_user.id)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/collections_helper.rb
module CollectionsHelper

  def genres_collection
    @genres_collection ||= Genre.all.map {|genre| [genre.classification, genre.id]}
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/views/admin/genres/_form.html.erb
<div class="">
  <%= form_for [:admin, @genre] do |f| %>
    <%= f.text_field :classification %>

    <%= f.submit %>
  <% end %>
</div>

app/views/admin/genres/new.html.erb
<div id="new-genre-page">
  <section id="dashboard-backlink">
    <%= link_to "Back", admin_dashboard_path %>
  </section>
  <section id="new-genre-box">
    <div id="new-genre-text">
      <p>Create a Genre</p>
    </div>
    <div id="new-genre-form">
      <%= render partial: "form" %>
    </div>
  </section>
</div>

app/views/admin/images/_form.html.erb
<div id="image-box">
  <%= form_for [:admin, @image] do |f| %>
  <section class="image-boxes">
    <%= f.label :image, "Choose Image" %>
    <%= f.file_field :image %>
  </section>
  <section class="image-boxes">
    <%= f.label :name, "Image Name" %>
    <%= f.text_field :name %>
  </section>
  <section class="image-boxes-button">
    <%= f.submit "Upload" %>
  </section>
  <% end %>
</div>

app/views/admin/images/new.html.erb
<section id="new-genre-page">
  <div id="dashboard-backlink">
    <%= link_to "Back", admin_dashboard_path %>
  </div>
  <div id="new-genre-box">
    <section id="new-genre-text">
      <p>Image Uploader</p>
    </section>
    <section id="new-genre-form">
      <%= render partial: "form" %>
    </section>
  </div>
</section>

app/views/concerts/_form.html.erb
<div id="session-new-form">
  <%= form_for [current_user, @concert] do |f| %>
    <section class="session-form-elements">
      <%= f.label :name, "Event Name" %>
      <%= f.text_field :name, required: true, maxlength: 25 %>
    </section>
    <section class="session-form-elements">
      <%= f.label :purchased, "Check if Ticket Purchased" %>
      <%= f.check_box :purchased %>
    </section>
    <section class="session-form-elements">
      <%= f.label :date %>
      <%= f.date_field :date, required: true %>
    </section>
    <section class="session-form-elements">
      <%= f.label :genre_id %>
      <%= f.collection_select(:genre_id, @genres, :id, :classification ) %>
    </section>
    <section class="session-form-elements">
      <%= f.label :image, "Select an Image" %>
      <%= f.collection_select(:image_ids, @images, :id, :name) %>
      <%= link_to "View Images", images_path %>
    </section>
    <section id="concert-form-button">
      <%= f.submit "Set Reminder" %>
    </section>
  <% end %>
</div>

app/views/concerts/edit.html.erb
<section id="concert-edit">
  <div id="concert-edit-header">
    <%= link_to "Back", edit_user_concert_path(current_user, params[:id]) %>
  </div>
  <div id="concert-edit-box">
    <section id="new-concert-text">
      Edit A Concert
      <div id="session-new-form">
        <%= form_for [current_user, @concert] do |f| %>
          <section class="session-form-elements">
            <%= f.label :name, "Event Name" %>
            <%= f.text_field :name, required: true, maxlength: 25 %>
          </section>
          <section class="session-form-elements">
            <%= f.label :purchased, "Check if Ticket Purchased" %>
            <%= f.check_box :purchased %>
          </section>
          <section class="session-form-elements">
            <%= f.label :date %>
            <%= f.date_field :date, required: true %>
          </section>
          <section class="session-form-elements">
            <%= f.label :genre_id %>
            <%= f.collection_select(:genre_id, @genres, :id, :classification ) %>
          </section>
          <section class="session-form-elements">
            <%= f.label :image, "Select an Image" %>
            <%= f.collection_select(:image_ids, @images, :id, :name) %>
            <%= link_to "View Images", images_path %>
          </section>
          <section id="concert-form-button">
            <%= f.submit "Edit Reminder" %>
          </section>
        <% end %>
      </div>
    </section>
  </div>
</section>

app/views/concerts/new.html.erb
<section id="concert-new">
  <div id="concert-new-header">
    <%= link_to "Back", user_path(current_user) %>
  </div>
  <div id="session-new-box">
    <section id="new-concert-text">
      <h1>New Concert Reminder</h1>
    </section>
    <div id="session-new-form">
      <%= form_for [current_user, @concert] do |f| %>
        <section class="session-form-elements">
          <%= f.label :name, "Event Name" %>
          <%= f.text_field :name, required: true, maxlength: 25 %>
        </section>
        <section class="session-form-elements">
          <%= f.label :purchased, "Check if Ticket Purchased" %>
          <%= f.check_box :purchased %>
        </section>
        <section class="session-form-elements">
          <%= f.label :date %>
          <%= f.date_field :date, required: true %>
        </section>
        <section class="session-form-elements">
          <%= f.label :genre_id %>
          <%= f.collection_select(:genre_id, @genres, :id, :classification ) %>
        </section>
        <section class="session-form-elements">
          <%= f.label :image, "Select an Image" %>
          <%= f.collection_select(:image_ids, @images, :id, :name) %>
          <%= link_to "View Images", images_path %>
        </section>
        <section id="concert-form-button">
          <%= f.submit "Create Reminder" %>
        </section>
      <% end %>
    </div>
  </div>
</section>

app/views/concerts/show.html.erb
<div id="concert-show">
  <section id="back-button">
    <%= link_to "Back", user_path(current_user) %>
  </section>
  <section id="concert-show-card">
    <div id="concert-info">
      <section>
        <%= @concert.name %></br>
        in <%= @concert.time_until %>
      </section>
      <section>
        Genre - <%= @concert.genre.classification %>
      </section>
      <section>
        Ticket Purchased? <%= @concert.purchased? %>
      </section>
    </div>
    <div>
      <% @concert.images.each do |image| %>
      <%= image_tag image.image.url unless image.image.url.nil?  %>
      <% end %>
    </div>
    <div id="date">
      <%= @concert.readable_date %>
    </div>
    <div id="concert-show-buttons" >
      <%= link_to "Edit", edit_user_concert_path(current_user, @concert) %>
      <%= link_to "Delete", user_concert_path(current_user, @concert), method: :delete %>
    </div>
  </section>
</div>

app/views/images/index.html.erb
<section id="image-index">
  <div id="image-index-button">
    <%= link_to "Back", new_user_concert_path(current_user) %>
  </div>
  <div id="image-index-area">
    <% @images.each do |image| %>
      <section id="image">
        <%= image_tag image.image.url unless image.image.url.nil? %>
      </section>
    <% end %>
      <section>
        <%= will_paginate @images %>
      </section>
  </div>
</section>

app/views/users/_nav.html.erb
  <div class="tooltip">
    <%= link_to image_tag("logos/admin.png"), admin_dashboard_path if current_admin? %>
    <span class="tooltiptext">Admin Access</span>
  </div>
  <div class="tooltip">
    <%= link_to image_tag("logos/calendaricon.png"), new_user_concert_path(current_user) %>
    <span class="tooltiptext">Set Reminder</span>
  </div>
  <div class="tooltip">
    <%= link_to image_tag("logos/logout.png"), logout_path, method: :delete, data: { confirm: 'Are you sure you want to log out?' } if logged_in? %>
    <span class="tooltiptext" id="nav-logout"><p>Log Out</p></span>
  </div>

app/views/users/new.html.erb
<div id="session-new-page">
  <section id="session-new-box">
    <div id="login-logo-div">
      <p id="session-logo-text">New Account</p>
    </div>
    <div id="session-new-form">
      <%= form_for @user do |f|  %>
      <section class="session-form-elements">
        <%=  f.label :name %>
        <%= f.text_field :name %>
      </section>
      <section class="session-form-elements">
        <%=  f.label :email %>
        <%= f.email_field :email %>
      </section>
      <section class="session-form-elements">
        <%=  f.label :password %>
        <%= f.password_field :password %>
      </section>
      <section class="session-form-elements">
        <%=  f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>
      </section>
      <section id="user-form-button">
        <%= link_to "Back", login_path %>
        <%= submit_tag("Reset Form", { :name => 'reset', :id => 'reset_button', :type => "reset" }) %>
        <%= f.submit "Create" %>
      </section>
      <% end %>
    </div>
  </section>
</div>

app/views/users/show.html.erb
<section class="show">
  <div id="header">
    <section class="user-show-header">
      <section id="show-logo">
        <p>concertBox</p>
      </section>
      <section id="nav-link">
        <%= render partial: "nav" %>
      </section>
    </section>
    <section class="sort-bar">
      <%= form_for(@search, url: user_path, method: :get) do |f| %>
      <%= f.label :genre, "Sort Concerts by Genre" %>
      <%= f.select :genre, genres_collection, include_blank: "All Genres" %>

      <%= f.label :purchased, "Tickets Purchased?" %>
      <%= f.select :purchased, [["Yes", true], ["No", false]], include_blank: "---" %>

      <%= f.label :name_like, "Search Concerts by Name" %>
      <%= f.text_field :name_like %>

      <%= submit_tag("Reset Form", { :name => 'reset', :id => 'reset_button', :type => "reset" }) %>
      <%= f.submit "Search" %>
      <% end %>
    </section>
  </div>
  <div class="concert-card-parent">
    <% if @concerts.any?%>
      <% @concerts.each do |concert| %>
        <%= link_to user_concert_path(current_user, concert) do %>
          <section class="concert-card-child">
            <div id="genre">
              <%= concert.genre.classification %>
            </div>
            <div class="concert-image">
              <% concert.images.each do |image| %>
              <%= image_tag image.image.url unless image.image.url.nil?  %>
              <% end %>
            </div>
            <div class="concert-name">
              <%= concert.name %>
              <p>in</p>
              <%= concert.time_until %>
            </div>
          </section>
        <% end %>
      <% end %>
    <% else %>
      <p id="no-matches">No matches.</p>
    <% end %>
  </div>
  <div class="apple_pagination">
    <%= will_paginate @concerts %>
  </div>
</section>